### ISSUE TITLE
Add release for alpha 3

### ISSUE THREAD

**Issue by Cilenco** [MTCKC/ProconXInput#10]
Can you please add a release for alpha 3?

Also does alpha 3 support rumble? The source looks like it does...

**Comment by MTCKC** [comment]
When I started working on ProconXInput, I naively implemented rumble thinking it worked like how most controllers do. However, Procon (and Joycon) rumble is implemented via linear actuators, not spinning weights. As such, how they're controlled is quite different, and the current implementation simply makes them vibrate a single time. That won't be ready by Alpha 3 since I need a way to test and debug it, and I have some things I want to add first like bluetooth support, multi-controller support (if it doesn't work currently, I have no way of checking currently since I only have a single wired Switch controller), and hotplugging.

Anyways, expect an Alpha 3 release this week. I have a chunk of free time for the first time since summer.
